# Generated by Tofuinit


output "vpc_id" {
  description = "The ID of the VPC created"
  value       = aws_vpc.main.id
}


output "private_subnet_ids" {
  description = "The IDs of the private subnets created"
  value       = aws_subnet.private.*.id
}


output "private_route_table_ids" {
  value       = aws_route_table.private.*.id
  description = "The IDs of the private route tables"
}
